name: first workflow

on:
  workflow_dispatch:
  issues:
    types: [opened]
env:
  test: "Step 1 complete!"
  test2: "Step 2 complete!"

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Job 1 Step 1
        run: echo ${{ env.test }}
      - name: Echo Job 1 Step 2
        run: echo ${{ env.test2 }}

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Cowsays
        uses: mscoutermarsh/cowsays-action@master
        with:
          text: 'Ready for prod–ship it!'
          color: 'magenta'
  
    
